# Generated by Django 2.2.1 on 2019-05-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_user_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wants_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
