# Generated by Django 2.2.1 on 2019-06-02 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190529_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cur_question',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='game',
            name='game_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='num_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='num_players',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GameQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Game')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Question')),
            ],
            options={
                'unique_together': {('game', 'index')},
            },
        ),
        migrations.CreateModel(
            name='GameAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesiton_index', models.IntegerField()),
                ('answer_index', models.IntegerField()),
                ('correct', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'user', 'quesiton_index')},
            },
        ),
    ]
