# Generated by Django 2.2.1 on 2019-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20190602_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_four_pts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_one_pts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_three_pts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_two_pts',
            field=models.IntegerField(default=0),
        ),
    ]
