# Generated by Django 2.2.1 on 2019-06-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20190602_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_questions',
            field=models.IntegerField(default=0),
        ),
    ]
