# Generated by Django 2.2.1 on 2019-06-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_game_num_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameanswers',
            old_name='quesiton_index',
            new_name='question_index',
        ),
        migrations.AlterUniqueTogether(
            name='gameanswers',
            unique_together={('game', 'user', 'question_index')},
        ),
    ]
