# Generated by Django 2.2.1 on 2019-06-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_report'),
        ('quiz', '0011_auto_20190602_1621'),
    ]

    operations = [
    ]
