# Generated by Django 2.2.1 on 2019-06-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_user_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_num_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='num_joins',
            field=models.IntegerField(default=0),
        ),
    ]
