# Generated by Django 2.2.1 on 2019-06-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20190607_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='max_num_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='num_joins',
        ),
        migrations.AlterField(
            model_name='user',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
